### ISSUE TITLE
Adding Transit Gateway Setup within the network settings description of MWAA docs

### ISSUE THREAD

**Issue by Zirkonium88** [awsdocs/amazon-mwaa-user-guide#11]
Hey there,

we configured our AWS environment within a central Network Operations Center (NoC) as described [here](https://d1.awsstatic.com/whitepapers/building-a-scalable-and-secure-multi-vpc-aws-network-infrastructure.pdf?did=wp_card&trk=wp_card).

Within this architecture, we were able to deploy MWAA with this template:

```YAML
# Snippet
Resources:
  MWAAdbt:
    Properties:
      AirflowConfigurationOptions:
        core.default_timezone: utc
        core.load_default_connections: true
        core.load_examples: false
        webserver.dag_default_view: tree
        webserver.dag_orientation: TB
      AirflowVersion: 2.0.2
      DagS3Path: dags
      EnvironmentClass: mw1.small
      ExecutionRoleArn:
        Fn::GetAtt:
        - mwaaservicerole
        - Arn
      KmsKey:
        Ref: DAGSBucketKey
      LoggingConfiguration:
        DagProcessingLogs:
          Enabled: true
          LogLevel: INFO
        SchedulerLogs:
          Enabled: true
          LogLevel: INFO
        TaskLogs:
          Enabled: true
          LogLevel: INFO
        WebserverLogs:
          Enabled: true
          LogLevel: INFO
        WorkerLogs:
          Enabled: true
          LogLevel: INFO
      MaxWorkers: 2
      Name: YOUR_MWAA
      NetworkConfiguration:
        SecurityGroupIds:
        - Fn::GetAtt:
          - SGMWAAEnvironmentEndpoints
          - GroupId
        SubnetIds:
        - subnet-AABBCC1
        - subnet-AABBCC2
      PluginsS3Path: packages/plugins.zip
      RequirementsS3Path: packages/requirements.txt
      SourceBucketArn:
        Fn::GetAtt:
        - mwaadags
        - Arn
      WebserverAccessMode: PRIVATE_ONLY
      WeeklyMaintenanceWindowStart: TUE:03:30
    Type: AWS::MWAA::Environment
  SGMWAAEnvironmentEndpoints:
    Properties:
      GroupDescription: MWAA and Interface Endpoint SG
      SecurityGroupEgress:
      - CidrIp: 0.0.0.0/0
        Description: Allow all outbound traffic by default
        IpProtocol: '-1'
      SecurityGroupIngress:
      - CidrIp: AAA.BB.CCC.DD/32
        Description: from AAA.BB.CCC.DD/32:443
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443
      - CidrIp: AAA.BB.CCC.DD/32:32
        Description: from AAA.BB.CCC.DD/32:5432
        FromPort: 5432
        IpProtocol: tcp
        ToPort: 5432
      VpcId: vpc-AABBCC
    Type: AWS::EC2::SecurityGroup
 SGMWAAEnvironmentEndpoint:
    Properties:
      Description: from SGMWAAEnvironmentEndpoint:ALL
        TRAFFIC
      GroupId:
        Fn::GetAtt:
        - SGMWAAEnvironmentEndpoints
        - GroupId
      IpProtocol: '-1'
      SourceSecurityGroupId:
        Fn::GetAtt:
        - SGMWAAEnvironmentEndpoints
        - GroupId
    Type: AWS::EC2::SecurityGroupIngress
  ```

The environment resides within a VPC (VpcId: vpc-AABBCC) which holds Route53 resolver rules to all necessary endpoints within our NoC account. These endpoints *do not share* the same Security Group, which is stated as mandatory [here: "One VPC security group. A VPC security group acts as a virtual firewall to control ingress (inbound) and egress (outbound) network traffic on an instance."](https://docs.aws.amazon.com/mwaa/latest/userguide/networking-about.html). 

From our on-premise networks (via Direct Connect terminating within NoC), we can now add IPs (AAA.BB.CCC.DD/32:443) to the endpoint security group (used by local MWAA endpoints) to make the access to MWAA possible via clicking the console link. We do not have local NAT or Internet Gateways. 

This is our favorite network setup and should be described within the documentation. We first tried the suggestion of the AWS support to create an internal ALB. But this just introduces operational overhead, as we figured out, that the endpoint access can be directly managed via Security Group adoption.

Probably useful for other enterprise customers.
